### ISSUE TITLE
Can't locate output from snk. Am I missing something?

### ISSUE THREAD

**Issue by Vortigern-The-Grey** [Platane/snk#116]
This is my workflow file:
```yaml
name: generate-snake-game-from-github-contribution-grid
# Controls when the workflow will run

on: # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  snek:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: Platane/snk@v3.2.0
        id: snake-gif
  
        with:
          github_user_name: Vortigern-The-Grey
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
My README:
```md
### Hi there 👋
![snek](https://github.com/Vortigern-The-Grey/Vortigern-The-Grey/blob/output/github-contribution-grid-snake.svg)
```
Do I have anything wrong?
