### ISSUE TITLE
[BUG] - The result of Generate Snake Actions only generates The Snake

### ISSUE THREAD

**Issue by vikingwarior** [Platane/snk#129]
Issue:
When I use the GitHub Action to generate the Animated Graph, it ends up creating a static image of the snake like shown below
![image](https://github.com/user-attachments/assets/46799cf4-0474-4079-8bc0-2f65b5aa96f9).

FYI I was referring to this article for implementing it: https://dev.to/mishmanners/how-to-enable-github-actions-on-your-profile-readme-for-a-contribution-graph-4l66  

I saw this exact issue with many other users who commented in this post that it is working for them. I think this issue might due to some changes in dependencies is what I suspect. 

This is the config I am trying to use for my main.yml file:

```
name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: vikingwarior
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
