### ISSUE TITLE
Invalid type and bad indentation errors

### ISSUE THREAD

**Issue by askiiart** [Platane/snk#52]
I'm trying to do the svg-only version of this, so I put this in my file:
```yml
- uses: Platane/snk/svg-only@v2
  with:
    outputs:
      dist/github-snake.svg
      dist/github-snake-dark.svg?palette=github-dark
```
That gives me the error "Invalid type found: `object` was expected but an array was found"

So then I fixed that by remove the `- ` before `uses:`, making it this:
```
uses: Platane/snk/svg-only@v2
  with:
    outputs:
      dist/github-snake.svg
      dist/github-snake-dark.svg?palette=github-dark
```
But then I get the error "bad indentation of a mapping entry"

**Comment by Platane** [comment]
you forgot the `|`

```yaml
uses: Platane/snk/svg-only@v2
  with:
    outputs: |  # <---- !
      dist/github-snake.svg
      dist/github-snake-dark.svg?palette=github-dark
```

outputs is actually a multi line string, gh action does not support array input (yet)
