### ISSUE TITLE
Error: Action failed with "Cannot read properties of null (reading '1')"

### ISSUE THREAD

**Issue by Life4gal** [Platane/snk#55]
The workflow I used in the beginning was like this:
```yml
name: github-contribution-grid-snake

on:
    schedule:
        - cron: "0 */12 * * *"
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        
        steps:
            - name: generate animation.svg
              uses: Platane/snk@master
              with:
                  github_user_name: ${{ github.repository_owner }}
                  svg_out_path: dist/github-contribution-grid-snake.svg
            
            - name: push github-contribution-grid-snake.svg to the snake_branch branch
              uses: crazy-max/ghaction-github-pages@v3
              with:
                  target_branch: snake_branch
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
It works fine, there is only one problem...
![image](https://user-images.githubusercontent.com/52756109/210920072-ba8d2a65-0837-4fd3-a66e-e91cac7d7a32.png)

I didn't like the warning, so I tried to fix it. I noticed that the version I was using was `Platane/snk@master`, so I came here to try to find a more recent (Release) version, and I saw that the most recent Release was v2.1.0, so I changed the workflow to that:

```yml
name: github-contribution-grid-snake

on:
    schedule:
        - cron: "0 0 * * *"
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        
        steps:
            - name: generate animation.svg
              uses: Platane/snk@v2.1.0
              with:
                  github_user_name: ${{ github.repository_owner }}
                  # list of files to generate.
                  # one file per line. Each output can be customized with options as query string.
                  #
                  #  supported options:
                  #  - palette:     A preset of color, one of [github, github-dark, github-light]
                  #  - color_snake: Color of the snake
                  #  - color_dots:  Coma separated list of dots color.
                  #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
                  #                 Exactly 5 colors are expected.
                  outputs: |
                    dist/github-contribution-grid-snake.svg
                    dist/github-contribution-grid-snake-dark.svg?palette=github-dark
                    dist/github-contribution-grid-snake-ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            
            - name: push github-contribution-grid-snake.svg to the snake_branch branch
              uses: crazy-max/ghaction-github-pages@v3
              with:
                  target_branch: snake_branch
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Then it doesn't work and generates an error.
![image](https://user-images.githubusercontent.com/52756109/210920523-9bbfd673-9003-4917-8dd9-9838cafaedd8.png)

I noticed that a similar question was raised earlier in #35, but that's obviously a different question from mine.
