### ISSUE TITLE
[Bug] Snake rendering Bug

### ISSUE THREAD

**Issue by ramazansancar** [Platane/snk#58]
I'm having a little trouble creating a snake. Can you help me?

Same situation in svg and gif.

![image](https://user-images.githubusercontent.com/8878055/211163959-123c763f-15b7-4ccd-92a8-94752e86672b.png)

https://github.com/ramazansancar/ramazansancar/blob/output/github-contribution-grid-snake.svg

**Comment by muhammad-mobeen** [comment]
Yes, the same issue happening to me.

**Comment by srihar5ha** [comment]
My snake's not moving!!  :D

**Comment by VikashPR** [comment]
I am facing same issue too

**Comment by micaelmz** [comment]
same here

**Comment by ramazansancar** [comment]
> My snake's not moving!!  :D 

You need to feed your snake :P

**Comment by Platane** [comment]
it's fixed on the v2 version

Here is an [example config using the v2](https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml#L23-L31) : 
```yaml

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

```

for some context about the error: https://github.com/Platane/snk/issues/54#issuecomment-1373291774
