### ISSUE TITLE
Failure to run action.

### ISSUE THREAD

**Issue by eggnaut** [Platane/snk#63]
I thought 4th time would be the charm 😭

As per the [marketplace instructions](https://github.com/marketplace/actions/generate-snake-game-from-github-contribution-grid), I clicked 'Use latest version'.
Next, I copied the text it told me to, and headed over to my profile repo.
I went to Github Actions and clicked "set up a workflow yourself".
I dumped the text into the "main.yml" file and committed the changes. 
I head back to Actions and get this:
![Screen Shot 2023-01-14 at 7 03 15 PM](https://user-images.githubusercontent.com/120997069/212520757-af2fb2f8-1645-4cee-aa2e-6ca342f425e4.png)
![Screen Shot 2023-01-14 at 7 03 04 PM](https://user-images.githubusercontent.com/120997069/212520758-2299a33b-5306-4507-b9cf-b7be6322b5a8.png)

Please help! I do feel instructions could be more detailed/clearer, but maybe it's just me :P

**Comment by eggnaut** [comment]
And when I figure this out, could someone guide me on getting dark mode? Thanks!

**Comment by fky2015** [comment]
This is my GitHub Actions file (And you can see the whole [file structures here](https://github.com/fky2015/fky2015/tree/e5f2395a034c25070c31f9db68d17bd9bb48ddf0)):
```yml
name: generate animation

on:
  # run automatically every day
  schedule:
    - cron: "0 6 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

My suggestion is that, to fully understand GitHub Actions, please give a look at the [official documentation](https://docs.github.com/en/actions).
