### ISSUE TITLE
Suddenly commits doesn't appears and snake dont move

### ISSUE THREAD

**Issue by gatavares** [Platane/snk#91]
I have this snake since july and works prettie well but now does not show anything :(
If anyone knows what happens and can help I appreciate it!

Look like this ;-;
![image](https://github.com/Platane/snk/assets/75699007/5ad85740-ccc2-407e-a34e-71d9b158d9b4)

**Comment by Platane** [comment]
you are running an version that is no longer maintained, sorry

replace
```yml
- uses: Platane/snk@master
  id: snake-gif
    with:
      github_user_name: gatavares
      svg_out_path: dist/github-contribution-grid-snake.svg
```

by

```yml
- uses: Platane/snk/svg-only@v3
  id: snake-gif
  with:
    github_user_name: gatavares
    outputs: |
      dist/github-contribution-grid-snake.svg
```
