### ISSUE TITLE
Github actions workflow failing to generate SVG images

### ISSUE THREAD

**Issue by stepbystepcode** [Platane/snk#97]
The Github actions workflow in the Platane/snk repository has recently stopped working properly when trying to generate SVG images of GitHub contribution grids.

Specifically, on October 5, 2023 the workflow started failing with an "Unauthorized" error when running the svg-only action. I have been using this successfully for some time, but now it fails with the following error when run:
```
Run Platane/snk/svg-only@v3
with:
  github_user_name: stepbystepcode  
  outputs:
    - dist/github-contribution-grid-snake.svg
    - dist/github-contribution-grid-snake-dark.svg?palette=github-dark

🎣 fetching github user contribution
Error: Action failed with "Unauthorized"
```
This prevents the SVG images from being generated as part of the workflow. Please look into what may have changed recently to cause this authentication error, and fix the workflow so it can generate the SVG images properly again. Let me know if any other info is needed to debug this issue.

Thanks!

**Comment by Lvjinhong** [comment]
I've encountered the same issue. Could you please provide further guidance on how to proceed

**Comment by JairTorres1003** [comment]
I've experienced the same issue recently, and I've found a solution that may help you. Based on what I discovered in this [issue #85](https://github.com/Platane/snk/issues/85#issuecomment-1653717918), it seems that the problem is related to the version of the workflow.

Up until now, I had been using version 2 (V2) of the workflow successfully. However, switching to version 3 (V3) resolved the issue, and the workflow started functioning correctly.

I hope this information proves helpful, and you can resolve the issue by transitioning to version 3 of the workflow! I greatly appreciate this project from @Platane

Greetings!

**Comment by stepbystepcode** [comment]
> I've experienced the same issue recently, and I've found a solution that may help you. Based on what I discovered in this [issue #85](https://github.com/Platane/snk/issues/85#issuecomment-1653717918), it seems that the problem is related to the version of the workflow.
> 
> Up until now, I had been using version 2 (V2) of the workflow successfully. However, switching to version 3 (V3) resolved the issue, and the workflow started functioning correctly.
> 
> I hope this information proves helpful, and you can resolve the issue by transitioning to version 3 of the workflow! I greatly appreciate this project from @Platane
> 
> Greetings!

Thanks, bro! It solved my problem!
This workflow works:
```yaml

name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
  

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
```
